[package]
name = "jgb-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
log = "0.4"
rand = "0.8"
sdl2 = "0.35"
thiserror = "1.0"