[workspace]
members = [
    "jgb-proc-macros",
    "jgb-core",
    "jgb-cli",
    "jgb-gui",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }

[profile.release-lto]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true
