[workspace]
members = [
    "jgb-proc-macros",
    "jgb-core",
    "jgb-cli",
    "jgb-gui",
]

[profile.release-lto]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true
