# https://github.com/ericseppanen/cargo-cranky
# Install: cargo install cargo-cranky
# Run: cargo cranky

warn = [
    "clippy::all",
    "clippy::pedantic",
    "rust_2018_idioms",
]

# Remove pedantic lints that have a high false positive rate or that I disagree with
allow = [
    "clippy::cast_possible_truncation",
    "clippy::cast_possible_wrap",
    "clippy::cast_precision_loss",
    "clippy::cast_sign_loss",
    "clippy::if_not_else",
    "clippy::inline_always",
    "clippy::module_name_repetitions",
    "clippy::needless_pass_by_value",
    "clippy::similar_names",
    "clippy::single_match_else",
    "clippy::stable_sort_primitive",
    "clippy::struct_excessive_bools",
    "clippy::unreadable_literal",
]
