[package]
name = "jgb-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgb-core = { path = "../jgb-core" }

eframe = "0.21"
egui = "0.21"
log = "0.4"
rfd = "0.11"
tracing-subscriber = "0.3"