name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check --verbose

    - name: Install libsdl2
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Check Clippy warnings
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Get latest tarpaulin version
      id: get-tarpaulin-version
      run: |
        cargo search cargo-tarpaulin | head -1 | cut -d' ' -f3 | sed -re 's/"(.*)"/version=\1/g' >> $GITHUB_OUTPUT

    - name: Cache tarpaulin binary
      id: tarpaulin-cache
      uses: actions-rs/cache@v3
      with:
        path: ~/.cargo/bin/tarpaulin
        key: ${{ runner.os }}-${{ steps.get-tarpaulin-version.outputs.version }}

    - name: Install tarpaulin
      if: steps.tarpaulin-cache.outputs.cache-hit != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-tarpaulin --version ${{ steps.get-tarpaulin-version.outputs.version }}

    - name: Generate code coverage report
      uses: actions-rs/cargo@v1
      with:
        command: tarpaulin
        args: --out Xml

    - name: Upload code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-xml
        path: cobertura.xml
